livecodes/gardens-and-plants/config/routes.rb
Rails.application.routes.draw do
  root to: 'gardens#index'
  resources :gardens, only: [:index, :show] do
    resources :plants, only: :create
  end
  resources :plants, only: :destroy do
    resources :plant_tags, only: [:new, :create]
  end
end

livecodes/gardens-and-plants/app/models/garden.rb
class Garden < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
  has_many :plants, dependent: :destroy
end

livecodes/gardens-and-plants/app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
  has_many :plant_tags, dependent: :destroy
  has_many :tags, through: :plant_tags

  validates :name, :image_url, presence: true
end

livecodes/gardens-and-plants/app/models/plant_tag.rb
class PlantTag < ApplicationRecord
  belongs_to :plant
  belongs_to :tag

  validates :tag, uniqueness: { scope: :plant }
  # validates :plant, uniqueness: { scope: :tag }
end

livecodes/gardens-and-plants/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :plant_tags, dependent: :destroy
  has_many :plants, through: :plant_tags
end

livecodes/gardens-and-plants/app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[ show edit update destroy ]

  # GET /gardens
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1
  def show
    @plant = Plant.new
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit
  end

  # POST /gardens
  def create
    @garden = Garden.new(garden_params)

    if @garden.save
      redirect_to @garden, notice: 'Garden was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /gardens/1
  def update
    if @garden.update(garden_params)
      redirect_to @garden, notice: 'Garden was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /gardens/1
  def destroy
    @garden.destroy
    redirect_to gardens_url, notice: 'Garden was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def garden_params
      params.require(:garden).permit(:name, :banner_url)
    end
end

livecodes/gardens-and-plants/app/controllers/plant_tags_controller.rb
class PlantTagsController < ApplicationController
  def new
    @plant = Plant.find(params[:plant_id])
    @plant_tag = PlantTag.new
  end

  def create
    @plant = Plant.find(params[:plant_id])
    tags = Tag.where(id: tag_params[:tag_id])
    tags.each do |tag|
      plant_tag = PlantTag.new(plant: @plant, tag: tag)
      plant_tag.save
    end

    redirect_to garden_path(@plant.garden)
  end

  private

  def tag_params
    params.require(:plant_tag).permit(tag_id: [])
  end
end

livecodes/gardens-and-plants/app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    @plant = Plant.new(plant_params)
    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden
    if @plant.save
      redirect_to garden_path(@garden)
    else
      render 'garden/show'
    end
  end

  private
  
  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

livecodes/gardens-and-plants/app/helpers/gardens_helper.rb
module GardensHelper
end

livecodes/gardens-and-plants/app/helpers/plant_tags_helper.rb
module PlantTagsHelper
end

livecodes/gardens-and-plants/app/helpers/plants_helper.rb
module PlantsHelper
end

livecodes/gardens-and-plants/app/views/gardens/index.html.erb
<div class="container">
  <h1 class="m-5 text-center">My favorite gardens</h1>
  <div class="row">
    <% @gardens.each do |garden| %>
      <div class="col-4">
        <%=  link_to garden_path(garden) do %>
          <div class="card-trip mb-3">
            <img src="<%= garden.banner_url %>" />
            <div class="card-trip-infos">
              <div>
                <h2><%= garden.name %></h2>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

livecodes/gardens-and-plants/app/views/gardens/show.html.erb
<div class="banner mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-8">
      <% if @garden.plants.any? %>
        <div class="container">
          <div class="row">
            <% @garden.plants.each do |plant| %>
              <div class="col-6">
                <div class="card-trip">
                  <div class="card-tags">
                    <% plant.tags.each do |tag| %>
                      <span><%= tag.name %></span>
                    <% end %>
                    <%= link_to "+", new_plant_plant_tag_path(plant) %>
                  </div>
                  <%= image_tag plant.image_url %>
                  <div class="card-trip-infos">
                    <div>
                      <h2><%= plant.name %></h2>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% else %>
        <h2>No plants in this garden yet, add some!</h2>
      <% end %>
    </div>
    <div class="col-4">
      <h2>Add a plant:</h2>
      <%= simple_form_for [@garden, @plant] do |f| %>
        <%= f.input :name, placeholder: 'Sakura' %>
        <%= f.input :image_url %>
        <%= f.submit 'Add', class:"btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

livecodes/gardens-and-plants/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

livecodes/gardens-and-plants/app/views/plant_tags/create.html.erb
<h1>PlantTags#create</h1>
<p>Find me in app/views/plant_tags/create.html.erb</p>

livecodes/gardens-and-plants/app/views/plant_tags/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-md-8">
      <h1>Add new tag for <%= @plant.name %></h1>
      <%= simple_form_for([@plant, @plant_tag]) do |f| %>
        <%= f.association :tag, input_html: { multiple: true, class: 'multiple-select' }, include_hidden: false %>
        <%= f.submit 'Add tag', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>